### ISSUE TITLE
bug: including the google.protobuf types breaks the code

### ISSUE THREAD

**Issue by bartek1912** [cpcloud/protoletariat#45]
Hello, 
Whenever I add gRPC [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) like Empty, the protoletariat breaks the python code changing:
```
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
```
to
```
from .google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
```

**Comment by cpcloud** [comment]
Thanks for the report. I should be able to look into this later tonight or tomorrow morning.

**Comment by cpcloud** [comment]
@bartek1912 The PR will be merged shortly and a release automatically cut to PyPI and `ghcr.io` shortly thereafter. Thanks for reporting this.

**Comment by bartek1912** [comment]
Thanks! ;)
