### ISSUE TITLE
Generated .pyi files include __pycache__, are not idempotent

### ISSUE THREAD

**Issue by lidavidm** [cpcloud/protoletariat#477]
I've noticed a few things about generated `.pyi` files:

- `__pycache__` gets picked up and imported,
- Entries are not sorted (though this isn't really a big deal, it kinda helps with reviewing the diff)
- Entries get duplicated if run multiple times/generation is not idempotent

The last one is probably harder to solve since it appears Protoletariat is not assuming it has full control of the `pyi` (understandable), or else it could overwrite instead of append.

**Comment by cpcloud** [comment]
Sweet, thanks for the issue. I think we can probably address all three.

The last one may be a bit tricky as you say.

Maybe inserting a comment at the end like `# __protol__: $ORIGINAL_IMPORT` to indicate that the line came from `protol` and then leaving out duplicates during rewriting would work.

**Comment by lidavidm** [comment]
Frankly a simple string match is _probably_ enough, if janky

**Comment by cpcloud** [comment]
@lidavidm Do you have a concrete example of

> `__pycache__` gets picked up and imported,

I'm not seeing `.pyi` files inside of `__pycache__` anywhere.

**Comment by lidavidm** [comment]
Oh sorry, what I mean is it'll generate things like
```
from . import __pycache__
```
