### ISSUE TITLE
No such option `--descriptor_set_in`

### ISSUE THREAD

**Issue by bartek1912** [cpcloud/protoletariat#478]
It would be great if protoletariat would pass the `--descriptor_set_in` parameter to protoc compiler. Now it just returns an error:
```
Usage: protol protoc [OPTIONS] PROTO_FILES...
Try 'protol protoc --help' for help.

Error: No such option: --descriptor_set_in
```

**Comment by cpcloud** [comment]
Thanks for raising the issue! I think adding this argument makes sense. I wonder if click has a way to just dump everything beyond `--` to a subcommand.
