### ISSUE TITLE
Way of providing the descriptor set out manually

### ISSUE THREAD

**Issue by bartek1912** [cpcloud/protoletariat#51]
Hello,
Is there a way of providing the descriptor set out instead of calling protoc/buf? Now, it doubles the Python SDK generation time.

**Comment by cpcloud** [comment]
@bartek1912 Would something like

```sh
$ protol raw --descriptor-set path/to/descriptor/set/blob.proto.bin ...
```

and/or

```sh
$ protol raw ... < path/to/descriptor/set/blob.proto.bin
```

work?

**Comment by bartek1912** [comment]
The second one ;)
