### ISSUE TITLE
Usage with protobuf 4.*

### ISSUE THREAD

**Issue by burk** [cpcloud/protoletariat#571]
Hello!

This library requires protobuf<4. Are there any known issues using it with protobuf 4.*?

**Comment by cpcloud** [comment]
Not that I am aware of, I just haven't had the need to do that yet. Happy to look into it.

**Comment by burk** [comment]
That would be great! I was trying to upgrade since apparently protobuf 4 has some performance improvements. I can test it out if you want, once you've built a new package.
