### ISSUE TITLE
Using `import public` results in `from xxx_pb2 import *` statements that aren't converted

### ISSUE THREAD

**Issue by randombk** [cpcloud/protoletariat#784]
Hi!

The use of `import public` feature ([see docs](https://protobuf.dev/programming-guides/proto3/#importing-definitions)) results in `protoc` generating `from xxx_pb2 import *` statements, which aren't being properly converted.

For example, this happens if I change `import "thing2.proto";` line in the README example to `import public "thing2.proto";`.

**Comment by cpcloud** [comment]
Thanks for the report, I'm looking into it!

**Comment by cpcloud** [comment]
@randombk Thanks for the issue! Fix is up in #802.
